name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test_secret_repository
        run: |
          mkdir tmp
          echo $SECRET_REPOSITORY_TESTE > tmp/environment
          cat tmp/environment